spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA:public}&search_path==${POSTGRES_SCHEMA:public}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jta:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  activemq:
    broker-url: tcp://${ACTIVEMQ_HOST}:${ACTIVEMQ_PORT}
    user: ${ACTIVEMQ_USERNAME}
    password: ${ACTIVEMQ_PASSWORD}
server:
  port: ${APPLICATION_PORT:8080}
  servlet:
    context-path: /customer
logging:
  file:
    path: /var/log/customer
authenticationServiceURL: ${AUTH_URL}
authenticationServicePort: ${AUTH_PORT}