FROM amazoncorretto:21-alpine3.17 AS base
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

FROM base AS builder
ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

USER root

# Download gradle
RUN apk add unzip
RUN mkdir /usr/gradle
RUN wget -P /usr/gradle https://services.gradle.org/distributions/gradle-8.4-bin.zip
RUN unzip /usr/gradle/gradle-8.4-bin.zip -d /usr/gradle
ENV GRADLE_HOME=/usr/gradle/gradle-8.4
ENV PATH=$PATH:$GRADLE_HOME/bin

COPY ./build.gradle ./settings.gradle $APP_HOME

COPY ./build.gradle $APP_HOME/build.gradle
COPY ./settings.gradle $APP_HOME/settings.gradle

RUN gradle clean build --no-daemon > /dev/null 2>&1 || true

COPY ./src $APP_HOME/src

CMD [ "gradle", "bootrun", "--debug-jvm" ]
